drop table BBS;

CREATE TABLE BBS(
	SEQ INT AUTO_INCREMENT PRIMARY KEY,
	ID VARCHAR(50) NOT NULL,
	
	REF DECIMAL(8) NOT NULL,	---default 0
	STEP DECIMAL(8) NOT NULL,	---default 0
	DEPTH DECIMAL(8) NOT NULL,	---default 0
	
	TITLE VARCHAR(200) NOT NULL,
	CONTENT VARCHAR(4000) NOT NULL,
	WDATE TIMESTAMP NOT NULL,
	
	DEL DECIMAL(1) NOT NULL,	---default 0
	READCOUNT DECIMAL(8) NOT NULL	---default 0
);
--DATA: INSERT DELETE SELECT UPDATE
--OBJECT(TABLE):CREATE ALTER DROP
ALTER TABLE BBS
ADD
FOREIGN KEY(ID) REFERENCES MEMBER(ID);

INSERT INTO BBS(ID, REF, STEP, DEPTH,TITLE, CONTENT, WDATE, DEL, READCOUNT)
VALUES('jeongho0304', (SELECT IFNULL(MAX(REF), 0)+1 FROM BBS a),0,0, '제목입니다','내용입니다',NOW(),0,0);
--IFNULL(컬럼,값) 컬럼이 NULL이면 값을 대체용으로 넣은다 (NULL POINT EXCEPTION이 안나오게 하기 위해)

ALTER TABLE BBS AUTO_INCREMENT = 1;
DESC BBS;
DESC MEMBER;
SELECT * FROM BBS;
DELETE FROM BBS;

SELECT*FROM BBS;

-- 번호를 할당 ROW_NUMBER()
SELECT SEQ,ID, REF, STEP, DEPTH,TITLE, CONTENT, WDATE, DEL, READCOUNT
FROM
(SELECT ROW_NUMBER()OVER(ORDER BY REF DESC, STEP ASC) AS RNUM,
	SEQ,ID, REF, STEP, DEPTH,TITLE, CONTENT, WDATE, DEL, READCOUNT
FROM  BBS
ORDER BY REF DESC, STEP ASC) A
WHERE RNUM BETWEEN 1 AND 10;